name: Climbing Trees
favicon: null
layout_spectrum: 0.6522429343312979
typography_spectrum: 0.5458491207100451
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2687146607786417
  lightness: 0.2402458821889013
  saturation: 0.8776686815544963
  rhythmicContrast: 0.4573230042587966
purpose: []
